apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: argocd
spec:
  destination:
    name: 'artifactory'
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: nexus/platform/cicd/artifactory
    repoURL: 'https://github.com/shukla2009/helm-nginx.git'
    targetRevision: main
  project: default
