apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: nexus/microservice
    repoURL: 'https://github.com/shukla2009/helm-nginx.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
