apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: nexus/platform/apps
    repoURL: 'https://github.com/shukla2009/helm-nginx.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  
