apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: nexus/platform/cicd
    repoURL: 'https://github.com/shukla2009/helm-nginx.git'
    targetRevision: main
  project: default
